apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  strategy:
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: Ibrahim/activity4:app
        ports:
        - containerPort: 5500